//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZooApp.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZooBaseEntities : DbContext
    {
        public ZooBaseEntities()
            : base("name=ZooBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AllSex> AllSexes { get; set; }
        public virtual DbSet<BirdInfo> BirdInfoes { get; set; }
        public virtual DbSet<Employee> Employees { get; set; }
        public virtual DbSet<Food> Foods { get; set; }
        public virtual DbSet<Home> Homes { get; set; }
        public virtual DbSet<MarriedStatu> MarriedStatus { get; set; }
        public virtual DbSet<Pet> Pets { get; set; }
        public virtual DbSet<ReptileInfo> ReptileInfoes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TypeFood> TypeFoods { get; set; }
        public virtual DbSet<TypePet> TypePets { get; set; }
    }
}
