//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZooApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pet
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public int id_sex { get; set; }
        public Nullable<int> id_type { get; set; }
        public int id_food { get; set; }
        public int id_home { get; set; }
        public int id_smotritel { get; set; }
        public int id_doctor { get; set; }
        public Nullable<int> id_info_bird { get; set; }
        public Nullable<int> id_info_reptile { get; set; }
    
        public virtual AllSex AllSex { get; set; }
        public virtual BirdInfo BirdInfo { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Food Food { get; set; }
        public virtual Home Home { get; set; }
        public virtual ReptileInfo ReptileInfo { get; set; }
        public virtual TypePet TypePet { get; set; }
    }
}
